### ISSUE TITLE
[閒聊] 回覆自介！

### ISSUE THREAD

**Issue by DaisyMau** [c88tm/README#4]
1.為什麼可以接受早餐吃sukiya
2.哇我內雙
3.為什麼NS不玩漆彈
4.”不認為花一個小時等人一起吃飯是件值得的事情“ 我也贊同
5.你說話的體悟很酷

<end>

**Comment by c88tm** [comment]
1. 正常來說，我們會在 list 開頭的編號跟文字本體之間加一個空格
2. sukiya 的生蛋拌飯真的超讚，其實我只是單純喜歡吃生蛋拌飯，但是不知道 sukiya 以外的地方
3. 很棒，我喜歡你 ❤️ 
4. 漆彈不是要連線嗎，我又沒朋友QQ
5. 謝謝 www 我會盡力維持自己是個酷酷的人（？
